/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reflexion;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import java.sql.SQLException;

class EntityManagerImplTest {
	@Test
	public void testPersistence() {
		Club club = new Club();
		club.setFabricant("un nom");
		club.setPoids(10.3);
		
		EntityManagerImpl em = new EntityManagerImpl();
		em.persist(club);
		em.closeConnection();
	}
	
    @Test
    public void testFind() throws SQLException {
        Club club = new Club();
		club.setFabricant("un nom");
		club.setPoids(10.3);

		EntityManagerImpl em = new EntityManagerImpl();
		em.persist(club);
		
		Club trouve = em.<Club> find(Club.class, club.getId());
		Assertions.assertEquals(club.getFabricant(), trouve.getFabricant());
		em.closeConnection();
    }

	@Test
    public void testMerge() throws SQLException {
        Club club = new Club();
		club.setFabricant("un nom");
		club.setPoids(10.3);

		EntityManagerImpl em = new EntityManagerImpl();
		em.persist(club);
		
		club.setFabricant("un nouveau nom");
		club.setPoids(9.3);
		em.merge(club);

		Club trouve = em.<Club> find(Club.class, club.getId());
		Assertions.assertEquals(club.getFabricant(), trouve.getFabricant());
		em.closeConnection();
    }
}
