/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reflexion;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class EntityManagerImplTest {
    @Test void appHasAGreeting() {
        EntityManagerImpl classUnderTest = new EntityManagerImpl();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
